- packages/component-ui/src/radio/radio.tsx
コンポーネント Radio の修正依頼の対応を行いました。
https://www.notion.so/zenkigen/Radio-eb6d824d790b4a0690777f778fd8f415?pvs=4
input 要素が、13px となっていることを確認しましたが、
丸のサイズは、12px になっており、問題ないこと確認しました。
以下、操作改善のため修正を行いました。
- ホバー領域に関連し、操作の改善ができるとおもいましたので設定を行いました。
> Radio： input 要素にサイズ調整

- packages/component-ui/src/breadcrumb/breadcrumb-item.tsx
- packages/component-ui/src/breadcrumb/breadcrumb.tsx
コンポーネント Breadcrumb の修正依頼の対応を行いました。
https://www.notion.so/zenkigen/Breadcrumb-8ccea07ccb6c4f1099fb499467f0d3b0?pvs=4
> Breadcrumb：テキストカラー、ホバーエフェクトの修正

- packages/component-ui/src/dropdown/dropdown-menu.tsx
コンポーネント Dropdown の修正依頼の対応を行いました。
https://www.notion.so/zenkigen/Dropdown-f7391952a930475b8d1fe3a35ba0fbca?pvs=4
> Dropdown：リスト要素の上下 padding サイズの修正

- .storybook/main.ts
- package.json
- yarn.lock
@storybook/addon-links は @storybook/addon-essentials に含まれているため削除
> fix: @storybook/addon-actions を削除

- packages/component-ui/src/search/search.tsx
Search コンポーネント の修正を行いました。
https://zenkigen.slack.com/archives/C04V2HCBG4T/p1692282622891809
- onClickClearButtonがない場合はclearボタンを非表示に修正
- clearボタンを出さないケースを想定する
> fix: onClickClearButton がセットされてない場合は、clear ボタンを無効（非表示）に修正

- packages/component-ui/src/select-sort/select-sort.tsx
コンポーネント SelectSort の修正依頼の対応を行いました。
https://www.notion.so/zenkigen/ZENKIGEN-Component-29d4de3e60ad4e2d8e40f848ce4a253e?p=d69c04d7a326457fac9820444ceac817&pm=s
> fix: SelectSort: iconサイズの修正

- packages/component-ui/src/select/select.tsx
コンポーネント SelectSort の修正依頼の対応を行いました。
https://www.notion.so/zenkigen/ZENKIGEN-Component-29d4de3e60ad4e2d8e40f848ce4a253e?p=4c3bd48756224fecaadb7b67059fb215&pm=s
> fix: Select: iconサイズの修正

- packages/component-config/src/tokens/tokens.ts
- packages/component-config/style-dictionary/tokens.json
- packages/component-config/style-dictionary/transformed-tokens.json
アクセシビリティ向上のためGray70を更新したカラートークンを適用するPRです。
- 従来のGray70を新色（#6F7476）に更新（コントラスト比を確保する）
- Gray70が割り当てられていたセマンティックトークンを新色にし、Text02：Gray70、Text03：Gray60とする。
- ダークモードでは、Gray70が割り当てられていたセマンティックトークンをGray60に変更。
- 平塚さんがリストアップしてくれた更新内容
- [[アクセシビリティリサーチ](https://www.notion.so/e00af43b476745cd8cd2c279a3ec9499?pvs=21)](https://www.notion.so/e00af43b476745cd8cd2c279a3ec9499?pvs=21)
既存のzenkigen-compoentへの影響確認
- 更新したトークンの出現箇所をリストアップして視認性を確認し、特に問題ないと判断しています。
https://www.notion.so/zenkigen/UIUX-0c5dcdabdf704d43a63d35843386fd1b?p=fb1bcec5acd4412686dbc33eefc85b31&pm=s
> Feature/Update Tokens 230920

- packages/component-ui/src/select/select-item.tsx
- packages/component-ui/src/select/select-list.tsx
Select コンポーネントの改善を行いました。
- 再選択時に、選択済み要素が表示領域外にあり選択状態が不明な状態となっていたのを改善
maxHeight の指定がある場合に、以下となるよう対応した。
| Before | After |
| --- | --- |
| <img width="187" alt="image" src="https://github.com/zenkigen/zenkigen-component/assets/6478212/4b0b3eb1-5612-448f-9a8d-5163290b3574"> | <img width="182" alt="image" src="https://github.com/zenkigen/zenkigen-component/assets/6478212/22c9cb32-4404-4624-9a1e-81169a0f2201"> |
> refactor: Select 再選択時に選択済み要素が表示領域に配置されるよう調整

- packages/component-ui/src/dropdown/dropdown-context.ts
- packages/component-ui/src/dropdown/dropdown-menu.tsx
- packages/component-ui/src/dropdown/dropdown.stories.tsx
- packages/component-ui/src/dropdown/dropdown.tsx
Dropdown コンポーネントの改善を行いました。
- リスト部分を自由な位置に表示できるよう調整した
| Before | After |
| --- | --- |
|  | <img width="970" alt="image" src="https://github.com/zenkigen/zenkigen-component/assets/6478212/949df262-4131-4f2f-8262-e0a1e89027d9"> |
> feat: Dropdown リスト部分を自由な位置に表示できるよう調整

- packages/component-ui/src/select/select-list.tsx
プロダクト側のテストでコケる。
都度モックするのも冗長なのでここでチェックしてしまう。
> fix: test対応

- packages/component-ui/src/modal/modal-context.ts
- packages/component-ui/src/modal/modal-header.tsx
- packages/component-ui/src/modal/modal.stories.tsx
- packages/component-ui/src/modal/modal.tsx
modal のcloseボタンクリック時の制御方法の変更を行いました。
- Modal の prop setIsOpen を廃止
- Modal に prop onClose を新設
> feat: modal: closeボタンクリック時の制御方法の変更

- packages/component-ui/src/tooltip/tail-icon.tsx
- packages/component-ui/src/tooltip/tooltip.stories.tsx
- packages/component-ui/src/tooltip/tooltip.tsx
Tooltip 横位置 左右レイアウトの変更を行いました。
- horizontalAlign に left right  が指定された場合のレイアウトの変更を行いました。
> refactor: Tootip: 左右時のレイアウトの変更

- packages/component-ui/src/dropdown/dropdown.stories.tsx
- packages/component-ui/src/dropdown/dropdown.tsx
- packages/component-ui/src/table/table.stories.tsx
Dropdownのtargetにコンポーネントを入れた場合でもarrowを表示できるように調整してみました。
もともとisArrowHiddenのpropsがあったので、それをtargetを入れた場合でも使えるようにしただけです。
storyにはHeadingをtargetに入れた場合を並べました。
> Feature/Dropdown - add arrow to target

- packages/component-ui/src/tooltip/tooltip-content.tsx
- packages/component-ui/src/tooltip/tooltip.stories.tsx
- packages/component-ui/src/tooltip/tooltip.tsx
~~tooltip内で改行できるようにするために、pre-wrapのスタイルを追加した。~~
pre-wrapは影響が大きすぎるため、content を ReactNode にして使用するコンポーネント側で br タグを差し込む形に変更。
> feat: add style to tooltips

- packages/component-ui/src/pagination/pagination-button.tsx
- packages/component-ui/src/pagination/pagination.stories.tsx
- packages/component-ui/src/pagination/pagination.tsx
デザインレビューで確認・相談したstyle差分の修正です
・ボタンのwidthを`with可変=hug + padding: 4px + min-width: 32px`に修正
　（これに伴いButtonコンポーネントは使わないかたちにした）
・ボタン間のgapを4pxに修正
・両端のangleアイコンのサイズを修正
・数字3桁の場合を確認できるようにstoryを修正
修正前
修正後
> Pagination: Figmaとのstyle差分修正

- packages/component-ui/src/text-area/text-area.tsx
デザインレビューで確認・相談したstyle差分の修正です
・borderのカラートークン修正：uiBorder01 → uiBorder02
・size="large"の場合のline-heightを明示的に1.5に指定
　（Typographyトークンが足りない件は別途修正予定）
修正前
修正後
> TextArea: Figmaとのstyle差分修正

- packages/component-ui/src/text-input/text-input.tsx
デザインレビューで確認・相談したstyle差分の修正です
・borderのカラートークン修正：uiBorder01 → uiBorder02
・inputの高さをheightで指定するように修正
修正前
修正後
> TextInput: Figmaとのstyle差分修正

- .github/workflows/publish.yaml
- eslint.config.mjs
- package.json
- packages/component-config/package.json
- packages/component-config/src/index.ts
- packages/component-config/src/tailwind-config.ts
- packages/component-icons/package.json
- packages/component-theme/package.json
- packages/component-ui/package.json
- yarn.lock
- reactとreact-domをpeerdependenciesに追加する
- ビルドコマンドを2つ用意する
- storybook用: `yarn build` `yarn build:all`
- ライブラリ用: `yarn build-lib` `yarn build-lib:all`
> Reactをビルド生成物から取り除く

- packages/component-theme/src/colors.ts
＜問題＞
- Button コンポーネント
- variant outline
- 背景色が透明になっている
＜対応したこと＞
- 背景色をUiBackground01（#FFF）に設定
- component-theme の設定により適応されていた部分
- その修正を行った
| Before | After |
| --- | --- |
| <img width="956" alt="image" src="https://github.com/user-attachments/assets/9876cfd6-fe2a-41bc-9317-267f13501dcc" /> | <img width="957" alt="image" src="https://github.com/user-attachments/assets/3ec2e220-8835-4784-b08f-324e34d0dfda" /> |
> 61：Button：variant outline 背景色を白に修正

- packages/component-ui/src/tab/tab-item.tsx
Notion資料の②の部分
- Tab（未選択状態の）のホバー時の下線の色の token 変更
- 表示上の変更はなし（変更後のTokenが、元のTokenとカラーが同一のため）
> 35｜Tab｜Update hover background color for unselected tabs

- .gitignore
- packages/component-theme/src/colors.ts
- packages/component-ui/src/icon/icon.stories.tsx
- packages/component-ui/src/icon/icon.tsx
Icon コンポーネントから Dark variant の色指定 (icon01Dark, icon02Dark, icon03Dark) を削除
- `packages/component-theme/src/colors.ts` から iconColors オブジェクトの Dark 関連プロパティを削除 (icon01Dark, icon02Dark, icon03Dark)
- `packages/component-ui/src/icon/icon.tsx` の Icon コンポーネントから Dark variant の条件付きクラスを削除
- `packages/component-ui/src/icon/icon.stories.tsx` の Storybook の例からも Dark variant の表示部分を削除
- Design token 自体からは Dark variant は削除していません (他のコンポーネントでの使用の可能性があるため)
- Color type は `keyof typeof iconColors` として定義されているため、Dark variant 削除後は自動的に型から削除されます
> 98｜Icon｜refactor: remove dark icon variants from Icon component

- .github/workflows/chromatic.yaml
**1. github.event.pull_request.draft == false**
意味: プルリクエストがドラフト状態ではない
目的: ドラフトPRではChromaticテストを実行しない（開発中のため）
**2. contains(github.event.pull_request.labels.*.name, 'renovate') == false**
意味: プルリクエストにrenovateラベルが付いていない
目的: Renovateボット（依存関係自動更新ツール）によるPRではChromaticテストをスキップ
**3. contains(github.event.pull_request.labels.*.name, 'dependencies') == false**
意味: プルリクエストにdependenciesラベルが付いていない
目的: 依存関係更新のPRではChromaticテストをスキップ
> Chromaticデプロイメントジョブの実行条件の変更

- packages/component-config/src/tokens/tokens.ts
- packages/component-config/style-dictionary/tokens.json
- packages/component-config/style-dictionary/transformed-tokens.json
- packages/component-ui/src/toggle/toggle.tsx
Toggleコンポーネントの非選択時hoverカラーを新規トークン（hoverGray）に変更し、デザイン仕様に合わせるため。
- 新規トークン `hoverGray` を `component-config` のtokensに追加
- style-dictionaryのjson・transformed-tokens.jsonに `HoverGray` を追加
- Toggleコンポーネントの非選択時hoverカラーを `hoverGray` に変更
- Toggleコンポーネント（`component-ui`）
- トークン管理（`component-config`）
- Toggleコンポーネントの非選択時にhoverした際、指定のグレー色（#454A4D）が適用されることを確認
- 既存の他のトークン・コンポーネントへの影響がないことを確認
- デザインシステムのガイドラインに準拠
- 追加トークンは今後他コンポーネントでも利用可能
> 32, 94｜ColorToken, Toggle｜feat: add hoverGray token and apply to Toggle hover state

- packages/component-ui/src/modal/Docs.mdx
- packages/component-ui/src/modal/modal.stories.tsx
- packages/component-ui/src/modal/modal.tsx
- Modalコンポーネントに `maxWidth` プロパティを追加し、レスポンシブ対応・柔軟なレイアウト調整を可能にしました。
- 合わせてstorybook, docsの更新も行いました
- `maxWidth` プロパティを追加
- 任意のCSS幅指定（例: `'600px'`, `'80vw'` など）を受け付け、**デフォルト値は `'calc(100vw - 40px)'`** です。
- これにより、モバイル・PC問わず左右20pxの余白を保ちつつ、画面幅に応じて最大幅が自動調整されます。
- `maxWidth` を指定しない場合はこのデフォルト値が適用されます。
- `width` のデフォルト値は 480 ですが、`maxWidth` の制約も同時にかかります（例：width=600でも画面幅が狭い場合はmaxWidthが優先される）。
- 既存のAPI互換性は維持
- `maxWidth` の各パターン（デフォルト/カスタム値/レスポンシブ値）を確認できるストーリーを追加
- コントロールパネルから `maxWidth` を動的に変更可能
- 各プロパティの説明（argTypes）を充実化
- モーダルの開閉・ボタン操作の動作確認が容易になるようストーリーを改善
- Storybook上の説明文を拡充し、`maxWidth` の使い方や推奨値、注意点を明記
- Storybook上で全ストーリーが正しく動作することを確認
- `maxWidth` 指定時のレイアウト崩れがないことを確認
- ボタン押下時にモーダルが正しく閉じることを確認
- 既存のAPI互換性が維持されていることを確認
- 他機能・他コンポーネントへの影響なし
- 既存の利用箇所での破壊的変更なし
ることを確認
- `maxWidth` 指定時のレイアウト崩れがないことを確認
- …
> 142｜Modal｜feat: Improve Modal component (add max-width) and stories

- .github/workflows/chromatic.yaml
- .storybook/main.ts
- package.json
- packages/component-config/package.json
- packages/component-icons/package.json
- packages/component-icons/tsup.config.ts
- packages/component-theme/package.json
- packages/component-ui/package.json
- packages/component-ui/tsup.config.ts
- yarn.lock
> [!NOTE]
> ### 問題
> -  yarn build-storybook でエラー発生
> -  内部的に使用される Rollup 4.45.0 での問題
>    - 加え、microbundle が古すぎるRollupを使用している問題も関連
> -  作業時に手元のでエラー確認はできず
> ### 解決のために対応したこと
> -  ビルドツール microbundle をやめ、tsup に変更した
>    - microbundle が古すぎる問題は以前から認識、tsup に移行
>    -  Rollup 最新に統一されるも、4.45.0 ではエラーなので 4.44.0 に固定する対応を行った
>       -  4.45.0 のリリースが数日前ということもり、4.44.0に固定で対応
> -  chromatic まわりの設定の改善も合わせて行った
>    -  CI chromaui/action を v11からv13に上げた
>    -  Storybook 設定の見直し
>       -  不要な設定 vite-plugin-turbosnap の処理を削除
- 先の lock file maintenance 反映作業の影響
- https://github.com/zenkigen/zenkigen-component/pull/398
- 手元では動作問題なかったが、CIでエラーとなった
ChromaticのCI環境でStorybookビルド時に発生していた「Cannot add property 0, object is not extensible」エラーを解決しました。
- **エラー内容**: `Cannot add property 0, object is not extensible`
- …
> fix build errors in the Chromatic CI environment

- packages/component-config/src/tokens/tokens.ts
- packages/component-config/style-dictionary/tokens.json
- packages/component-config/style-dictionary/transformed-tokens.json
WCAG 2.1のコントラスト比要件を満たすため、テキストカラーとグレーカラーの値を調整しました。
- `packages/component-config/style-dictionary/tokens.json`
- Text02の参照値を`$Colors.Gray.Gray70` → `$Colors.Gray.Gray80`に変更
- Gray100の値を`#2F3233` → `#1F2121`に変更
以下のファイルは上記の変更に基づいてbuild処理で自動更新されました：
- `packages/component-config/src/tokens/tokens.ts`
- `packages/component-config/style-dictionary/transformed-tokens.json`
- **Text01**: `#2F3233` → `#1F2121` (より暗い灰色でコントラストを向上)
- **Text02**: `#6F7476` → `#5C6366` (より暗い灰色でコントラストを向上)
- **UiBackgroundTooltip**: `#2F3233` → `#1F2121` (Text01と同様)
- **BackgroundOverlayGray**: `#2f323380` → `#1f212180` (透明度付きで同様の調整)
- **ActiveLink02**: `#2F3233` → `#1F2121` (Text01と同様)
- **Gray100**: `#2F3233` → `#1F2121` (基準色の調整)
この変更により、以下の要素のコントラスト比が改善されます：
- プライマリテキスト（Text01）
- セカンダリテキスト（Text02）
- ツールチップの背景色
- …
> 68｜68-1, 68-2｜Fix WCAG 2.1 contrast ratio compliance

- packages/component-ui/src/pagination-select/pagination-select.tsx
color token `text03` の廃止に向けて、`text03` を `text02` に置き換える作業を実施しました。
WCAG2コントラスト要件への対応として、より適切なコントラスト比を持つトークンへの統一を図ります。
- `packages/component-ui/src/pagination-select/pagination-select.tsx`
- pagination-selectコンポーネント内のページ数表示部分で使用していた `text-text03` クラスを `text-text02` に変更
```diff
-        <div className="typography-label14regular text-text03">
+        <div className="typography-label14regular text-text02">
/ {pageMax}
{pageLabel}
</div>
```
- pagination-selectコンポーネントのページ数表示のテキストカラーが変更されます
- より適切なコントラスト比により、アクセシビリティが向上します
- color token text03 廃止に向けた一連の作業の一環
- WCAG2コントラスト改善対応
> 68｜68-3｜Fix WCAG 2.1 contrast ratio compliance
